drop table if exists flights cascade ;
drop table if exists tickets cascade ;
drop table if exists users cascade ;
drop sequence if exists flights_seq;
drop sequence if exists tickets_seq;
drop sequence if exists users_seq;
create sequence flights_seq start with 1 increment by 50;
create sequence tickets_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table flights (date_time timestamp(6), id bigint not null, primary key (id));
create table tickets (price numeric(38,2), flight_id bigint, id bigint not null, user_id bigint, place varchar(255), primary key (id));
create table users (money numeric(38,2), id bigint not null, name varchar(255), surname varchar(255), primary key (id));
alter table if exists tickets add constraint FKtdayegtd891qq5xm0axfbckvy foreign key (flight_id) references flights;
alter table if exists tickets add constraint FK4eqsebpimnjen0q46ja6fl2hl foreign key (user_id) references users;
drop table if exists flights cascade ;
drop table if exists tickets cascade ;
drop table if exists users cascade ;
drop sequence if exists flights_seq;
drop sequence if exists tickets_seq;
drop sequence if exists users_seq;
create sequence flights_seq start with 1 increment by 50;
create sequence tickets_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table flights (date_time timestamp(6), id bigint not null, primary key (id));
create table tickets (price numeric(38,2), flight_id bigint, id bigint not null, user_id bigint, place varchar(255), primary key (id));
create table users (money numeric(38,2), id bigint not null, name varchar(255), surname varchar(255), primary key (id));
alter table if exists tickets add constraint FKtdayegtd891qq5xm0axfbckvy foreign key (flight_id) references flights;
alter table if exists tickets add constraint FK4eqsebpimnjen0q46ja6fl2hl foreign key (user_id) references users;
drop table if exists flights cascade ;
drop table if exists tickets cascade ;
drop table if exists users cascade ;
drop sequence if exists flights_seq;
drop sequence if exists tickets_seq;
drop sequence if exists users_seq;
create sequence flights_seq start with 1 increment by 50;
create sequence tickets_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table flights (date_time timestamp(6), id bigint not null, primary key (id));
create table tickets (price numeric(38,2), flight_id bigint, id bigint not null, user_id bigint, place varchar(255), primary key (id));
create table users (money numeric(38,2), id bigint not null, name varchar(255), surname varchar(255), primary key (id));
alter table if exists tickets add constraint FKtdayegtd891qq5xm0axfbckvy foreign key (flight_id) references flights;
alter table if exists tickets add constraint FK4eqsebpimnjen0q46ja6fl2hl foreign key (user_id) references users;
